services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
    command: npx concurrently "react-scripts start" "nodemon --legacy-watch main.ts"

  prod:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      ports:
        - "8080:8080"
      command: npx ts-node main.ts