version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - .:/app
    command: npx concurrently "react-scripts start" "nodemon main.ts"

  prod:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      ports:
        - "443:443"
        - "80:80"
      command: ts-node main.ts